// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKbxKS2_NvsY3LpFGIvmGIWa1x8rzB7nE',
    appId: '1:357456522393:web:b0f977ee050c62ab145c08',
    messagingSenderId: '357456522393',
    projectId: 'pfa-tic-app',
    authDomain: 'pfa-tic-app.firebaseapp.com',
    storageBucket: 'pfa-tic-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMZMpLupeslVzA6Tn5dPC2l950qJB-WV4',
    appId: '1:357456522393:android:2ca4d2d99fde9a6c145c08',
    messagingSenderId: '357456522393',
    projectId: 'pfa-tic-app',
    storageBucket: 'pfa-tic-app.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKbxKS2_NvsY3LpFGIvmGIWa1x8rzB7nE',
    appId: '1:357456522393:web:3de2da2073258df4145c08',
    messagingSenderId: '357456522393',
    projectId: 'pfa-tic-app',
    authDomain: 'pfa-tic-app.firebaseapp.com',
    storageBucket: 'pfa-tic-app.appspot.com',
  );
}
